server:
  port: 5000
  host: 'localhost'

database:
  port: 5432
  host: 'localhost'
  user: 'postgres'
  password: 'phisio-log-dev'
  dbname: 'phisiolog'
  sslmode: 'disable' # For local development
