// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateHealthRecord(ctx context.Context, arg CreateHealthRecordParams) (HealthRecord, error)
	GetHealthRecord(ctx context.Context, id uuid.UUID) (HealthRecord, error)
}

var _ Querier = (*Queries)(nil)
